joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

gripper_controller:
  type: position_controllers/GripperActionController
  joint: main_gripper_joint_1
  goal_tolerance: 0.01
  stalled_velocity_threshold: 0.01
  stall_timeout: 0.2
  gains:
    gripper_joint: {p: 200, d: 1, i: 5, i_clamp: 1}
