product_id: 0x0008 # Dual adapter HS
#product_id: 0x0006 # ICS adapter HS

motor_0_driver:
  joint_name: main_gripper_joint_1
  id: 0
  min_angle: 0
  max_angle: 135
  stretch: 60
  speed: 127
  current_limit: 10
  temperature_limit: 80
  
